### ISSUE TITLE
bm-option can't be disabled

### ISSUE THREAD

**Issue by k-fish** [blessenm/ember-cli-bm-select#6]
It would be great if there was a way to disable bm-option so you could have disabled options like normal select boxes.

**Comment by blessenm** [comment]
Should be doable. I will look into it as soon as I get some free time.

**Comment by blessenm** [comment]
@k-fish  Options can now be disabled. You just need to set the `isDisabled` property of a `bm-option` to true.

    {{#bm-option data=item key="name" isDisabled=item.disabled}}
      {{item.name}}
    {{/bm-option}}

You can check out the [demo](http://blessanmathew.com/ember-cli-bm-select/) page to see it working.
Its available in the master branch.

**Comment by blessenm** [comment]
Publish to npm.
